export const ICD11_CODES = [
    { code: "DA00.0", name: "Cheilitis" },
    { code: "DA01.00", name: "Leukoplakia" },
    { code: "DA01.10", name: "Oral aphthae or aphtha-like ulceration" },
    { code: "DA01.11", name: "Oral mucositis" },
    { code: "DA01.15", name: "Mouth ulcers" },
    { code: "DA01.20", name: "Giant cell granuloma, central" },
    { code: "DA01.30", name: "Cellulitis or abscess of soft tissues of the mouth" },
    { code: "DA01.41", name: "Denture hyperplasia" },
    { code: "DA02.1", name: "Xerostomia" },
    { code: "DA03.0", name: "Glossitis" },
    { code: "DA03.1", name: "Geographic tongue" },
    { code: "DA03.5", name: "Macroglossia" },
    { code: "DA04.2", name: "Sialoadenitis" },
    { code: "DA04.3", name: "Abscess of salivary gland" },
    { code: "DA04.4", name: "Sialolithiasis" },
    { code: "DA04.5", name: "Mucocele of salivary gland" },
    { code: "DA05", name: "Cysts of oral or facial-neck region" },
    { code: "DA05.0", name: "Developmental odontogenic cysts" },
    { code: "DA05.1", name: "Developmental nonodontogenic cysts of oral region" },
    { code: "DA06.0", name: "Inflammatory conditions of jaws" },
    { code: "DA07.8", name: "Impacted teeth" },
    { code: "DA08.0", name: "Dental caries" },
    { code: "DA09.0", name: "Pulpitis" },
    { code: "DA09.6", name: "Periapical abscess" },
    { code: "DA09.60", name: "Periapical abscess with facial involvement" },
    { code: "DA0A", name: "Certain specified disorders of teeth or supporting structures" },
    { code: "DA0B", name: "Gingival diseases" },
    { code: "DA0C", name: "Periodontal disease" },
    { code: "DA0C.0", name: "Acute periodontitis" },
    { code: "DA0C.31", name: "Noma" },
    { code: "DA0C.4", name: "Abscess of periodontium" },
    { code: "DA0D.1", name: "Gingival enlargement" },
    { code: "DA0E", name: "Dentofacial anomalies" },
    { code: "DA0E.0", name: "Major anomalies of jaw size" },
    { code: "DA0E.5", name: "Malocclusion" },
    { code: "DA0E.8", name: "Temporomandibular joint disorders" }
];
